# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChargebeeCli < Formula
  desc "Chargebee CLI — develop, test, and manage your Chargebee integration"
  homepage "https://github.com/jhuiting/chargebee-cli"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.5/chargebee-cli_0.1.5_darwin_amd64.tar.gz"
      sha256 "5c5d679112c8a264bf7bdf4fc8477e9ecfb78599484ce8ce8fed0dece40e7255"

      define_method(:install) do
        bin.install "cb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.5/chargebee-cli_0.1.5_darwin_arm64.tar.gz"
      sha256 "bb15e8bf9f2e1344f1c626440e6ebf35d41b7b49a659fde91ce8da8a97ca4dc3"

      define_method(:install) do
        bin.install "cb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.5/chargebee-cli_0.1.5_linux_amd64.tar.gz"
      sha256 "bb07fb47cb2f3e284b7f02dc3f02cafaf144b91fd5864a4d2bde4e62b180a93a"
      define_method(:install) do
        bin.install "cb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.5/chargebee-cli_0.1.5_linux_arm64.tar.gz"
      sha256 "bef16699b4091576caecff8fe935e96165c9364070a0c6fc15fa0b526ad8d2cb"
      define_method(:install) do
        bin.install "cb"
      end
    end
  end
end
