# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChargebeeCli < Formula
  desc "Chargebee CLI — develop, test, and manage your Chargebee integration"
  homepage "https://github.com/jhuiting/chargebee-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.1/chargebee-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "2ee7ceb2310cacac674faf4dae60542a38884d9ed137db6d3311089e3dcc8bb8"

      define_method(:install) do
        bin.install "cb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.1/chargebee-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "1e44515938c7c18f3a193b7b3ef0dbe3370350653c8c7500c690bccaa1621b16"

      define_method(:install) do
        bin.install "cb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.1/chargebee-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "e38b0243576f22d0400fd5287e3f5fd084a9faa6b876911add559f2954a4d740"
      define_method(:install) do
        bin.install "cb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.1/chargebee-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "ca067b46c2f9f0948e5b1bc8660036daf6d43b5afcecbd66ba697341ffbbf20a"
      define_method(:install) do
        bin.install "cb"
      end
    end
  end
end
