# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChargebeeCli < Formula
  desc "Chargebee CLI — develop, test, and manage your Chargebee integration"
  homepage "https://github.com/jhuiting/chargebee-cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.4/chargebee-cli_0.1.4_darwin_amd64.tar.gz"
      sha256 "14835c1d02291178604f445f8054d3b193ba367a4cc5c17db1ce499eb940a466"

      define_method(:install) do
        bin.install "cb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.4/chargebee-cli_0.1.4_darwin_arm64.tar.gz"
      sha256 "fc2efd892d2cd187e4ce60ef1713c5ab13699cd3b88e37bf3859e48e125a1259"

      define_method(:install) do
        bin.install "cb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.4/chargebee-cli_0.1.4_linux_amd64.tar.gz"
      sha256 "5b2f3127624378c924f5e18d90978db0e7591e53ba24d15bc88d129eeb7822a1"
      define_method(:install) do
        bin.install "cb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v0.1.4/chargebee-cli_0.1.4_linux_arm64.tar.gz"
      sha256 "d2c7190b07568800ddc40a201e1621e8850cfbea4e391abd9638d7d390964df2"
      define_method(:install) do
        bin.install "cb"
      end
    end
  end
end
