# This file was generated by GoReleaser. DO NOT EDIT.
cask "chargebee-cli" do
  name "chargebee-cli"
  desc "Chargebee CLI — develop, test, and manage your Chargebee integration"
  homepage "https://github.com/jhuiting/chargebee-cli"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cb"

  on_macos do
    on_intel do
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v#{version}/chargebee-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "bba04c493562e6ebca40897c0d9e13103fde463fd75786d0e5f390fca4b8a792"
    end
    on_arm do
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v#{version}/chargebee-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "c82c06268b79c5b00e2b15589adbea4470afbcdb679a7b313d6ee1614232d3fb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v#{version}/chargebee-cli_#{version}_linux_amd64.tar.gz"
      sha256 "abdb431b14989767b3cc28794db997f310091cdc1eae0f1517565c6e24375eb0"
    end
    on_arm do
      url "https://github.com/jhuiting/chargebee-cli/releases/download/v#{version}/chargebee-cli_#{version}_linux_arm64.tar.gz"
      sha256 "e20f6035a92d624fea30ad85fbf12e7ac570e7339b8b04cc118c62dc36f6ff14"
    end
  end

  # No zap stanza required
end
